### ISSUE TITLE
坐等郭神第三行代码

### ISSUE THREAD

**Issue by xiangshiweiyu** [guolindev/SunnyWeather#1]
其实，刚刚开始步入 Android 的时候，及其迷茫，在京第一份工作还被开了，之后仔细研读郭神“d第二行代码”三遍，手抄一遍，才有了继续从事Android  开发的信心，之后，总之谢谢郭神的启蒙，谢谢郭神 的 “第二行代码”将我领入 Android 开发这个深坑，祝郭神 身体健康，阖家欢乐，祝郭神新书大卖。如题。

**Comment by guolindev** [comment]
已经出版，多谢支持。
