### ISSUE TITLE
请教一下 郭霖大佬

### ISSUE THREAD

**Issue by zhoujianli1016** [guolindev/SunnyWeather#3]
在做天气实战的时候，如果将数据模型加上data关键字的声明。搜索请求status成功，但是body（place）为null。但是去掉data关键字之后，数据就可以正常显示。这是为什么呢？

**Comment by guolindev** [comment]
没遇到这种情况，而且你看一下这个项目的源码，模数模型上都是有data关键字声明的。

https://github.com/guolindev/SunnyWeather/blob/master/app/src/main/java/com/sunnyweather/android/logic/model/PlaceResponse.kt

https://github.com/guolindev/SunnyWeather/blob/master/app/src/main/java/com/sunnyweather/android/logic/model/DailyResponse.kt

**Comment by zhoujianli1016** [comment]
对，我就是对比了您github上的源码 和  公众号的随书源码后 发现的区别，然后就去掉了data关键字后 数据正常了
![QQ截图20201211111219](https://user-images.githubusercontent.com/22313845/101857127-c53fd380-3ba1-11eb-9e24-6810fb584c68.png)

**Comment by guolindev** [comment]
但问题是，你直接下载github这个项目的源码，是可以正常运行的，使用了data关键字也并不会出错。

**Comment by zhoujianli1016** [comment]
行，我仔细检查一下。多谢大佬
